server:
  port: 8085
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/personal?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
mybatis:
  type-aliases-package: com.example.demo
  mapper-locations: classpath:mapperxml/*.xml

